### PR TITLE
Compiler

### PR DESCRIPTION
**Pull request by Kalekdan**
---
Name: Compiler
About: Mani can now "compile" code into a runnable jar
---

**Is your PR related to a feature request or Bug report?**
If applicable, please list feature request number or bug report ID.
> #44 

**Describe your PR**
A clear and concise description of what your pull request is changing or adding.
> Added a new module to build a jar including mani code which can then be run in isolation and will run the code.

**Describe intended use**
A clear and concise description of the intended use of the feature. Along with example code.
> Mani files are put in the resources folder, with a single main.mni file. Then building will generate the jar

**Additional comments**
Add any additional comments or screenshots here.
> I am not particularly familiar with gradle so the current implementation replaces the existing build task. I would need some guidance in how to create a second separate task to build just the compiler jar

### CODE REVIEW

**Comment by Kalekdan** [comment]
This is complete apart from gradle task. Need to create a separate task that does not affect the main build task. Compilation task must:

- Set ManiCompiler as main class
- Include resources folder into jar
Not sure if this will need to be in a separate build.gradle file or can work in same file...

**Comment by crazywolf132** [comment]
@ManiOdin test this please.

**Comment by crazywolf132** [comment]
@Kalekdan Good work. It should be able to go into the same build file. Take a look at how the `gradle idea` task works

**Comment by Kalekdan** [comment]
This is working now. Mani can be compiled with gradle buildCompiler.
I'm not sure what the line `with jar` on line 45 does but I found some examples online and it seems to work for this. If you can enlighten me then please do 😂

**Comment by crazywolf132** [comment]
@Kalekdan please update the branch to follow the new structure if possible.

#65 implemented a new file structure

**Comment by Kalekdan** [comment]
@crazywolf132 I've updated so that the code for compiler is now at `src/com/mani/compiler/ManiCompiler.java `. Is this appropriate or should it be more like `src/com/mani/lang/compiler/ManiCompiler.java `

**Comment by crazywolf132** [comment]
First option sounds fine

**Comment by crazywolf132** [comment]
Are we ready to merge?

**Comment by Kalekdan** [comment]
> Are we ready to merge?

Yes

**Comment by crazywolf132** [comment]
Well done!

**Pull request merged**
