### PR TITLE
Fixed map naming newMap error #68

### PR DESCRIPTION
**Pull request by Kalekdan**
---
Name: Fixed map naming newMap error #68
---

**Is your PR related to a feature request or Bug report?**
If applicable, please list feature request number or bug report ID.
> #68 

**Describe your PR**
A clear and concise description of what your pull request is changing or adding.
> Fixed bug #68 where creating a map named newMap would throw an error when creating another map afterwards.

**How did you fix the bug?**
If applicable, how did you fix the bug? Please use code snippets too.
> Updated sdtlib to not use newMap as a keyword

### CODE REVIEW

**Comment by Kalekdan** [comment]
Ready to merge - (not sure why CI isn't running tests though @crazywolf132 ?)

**Comment by crazywolf132** [comment]
Seems as though circle-ci has pushed a silent change. It will now only build either commits or pull requests.

**Comment by crazywolf132** [comment]
I need to work out what is happening with @ManiOdin too

**Comment by crazywolf132** [comment]
I think i might make my own Ci server rather than using Jenkins, as it just flooded the 100gb hard drive, for 2 builds.

**Pull request merged**
