### PR TITLE
Intellij gradle builder

### PR DESCRIPTION
**Pull request by crazywolf132**
**Is your PR related to a feature request or Bug report?**
If applicable, please list feature request number or bug report ID.
> No

**Describe your PR**
A clear and concise description of what your pull request is changing or adding.
> Adds the ability to use `gradle idea`

**Describe intended use**
A clear and concise description of the intended use of the feature. Along with example code.
> It is used to generate the intellij project along with the run configurations

**How did you fix the bug?**
If applicable, how did you fix the bug? Please use code snippets too.
> N/A

**Is it in the form of a library**
 - [x] No
 
If applicable what is the library called?
> N/A

**Does your PR replace an existing system**
If applicable, please describe how this PR changes the use of a related item.
> N/A

**Additional comments**
Add any additional comments or screenshots here.

### CODE REVIEW

**Comment by ManiOdin** [comment]
@crazywolf132 and @Kalekdan The Gods seem to agree with this one...

Maybe we could merge it.

**Comment by crazywolf132** [comment]
@Kalekdan As we can see, the jenkins server works. But please don't merge this yet.

**Comment by Kalekdan** [comment]
I've been using gradle for this project inside intellij so far with no issues... or is this something separate

**Comment by crazywolf132** [comment]
This is something seperate. Rather than setting up intellij to work with the project. And creating the run configurations and all. 

This will do it all with `gradle idea`.

The amount of times I've had to blow away the project, and start fresh with intellij is killing me. So I'm doing this for people who are joining the project, but also for those of us who have to do what I'm doing.

**Comment by ManiOdin** [comment]
The Gods say no!

**Comment by crazywolf132** [comment]
@ManiOdin test this please

**Comment by ManiOdin** [comment]
The Gods say no!

**Comment by ManiOdin** [comment]
The Gods say no!

**Comment by ManiOdin** [comment]
The Gods say no!

**Comment by ManiOdin** [comment]
The Gods say no!

**Comment by crazywolf132** [comment]
@ManiOdin please test this.

**Comment by crazywolf132** [comment]
@ManiOdin test this please

**Comment by crazywolf132** [comment]
Going to merge. All tests pass. 

[ Mani Odin failed because the server crashed. ]

**Pull request merged**
