### PR TITLE
Added test for lists and maps functionality (#9)(#25)

### PR DESCRIPTION
**Pull request by Kalekdan**
Some functionality is commented out - it seems documentation may be slightly ahead of what Mani is currently capable of... unless I have made an error in the language.
_(Re-raised PR as issue number was wrong in previous)_

### CODE REVIEW

**Comment by crazywolf132** [comment]
The reason why some of the functions aren't working is because the docs were made based on the old system.

We then moved to a module system (`load "arrays";`) and they haven't been updated to it. As some of the modules now have different API functions so without the testing we didn't know that some of the standard library didn't work.

Give me an hour to get into the office, and I'll revise them.

**Comment by Kalekdan** [comment]
Ok no worries, no rush. I'm in the uk so won't be doing much more on it this evening anyway. I'll take a look updating the tests I'm writing and tweaking the docs as necessary.

**Comment by crazywolf132** [comment]
Try and follow #15 if you are looking for anything to do in the meantime

**Comment by crazywolf132** [comment]
@Kalekdan I have updated our system to use our own testing library (written in máni).

There is no need for the testing files that you have added in this PR now, as i have ported them over for you. I have given full credit to you on the work for the testing of these libraries.

There is still some work that needs to be done with them and some further testing (Maps library) with the fixes you propose inside this PR.

I would suggest you continue with creating testing cases, and follow the same procedure i have setup with the Lists and Maps files.

If you are looking for more things todo, we can always do with some help setting up some documentation around committing new features, and how they must have the correct tests added to them. Or even adding the new Testing library to the docs, so people know how to use it.

I myself will be going around and trying to add all the features i have implement recently into test cases.

**Comment by Kalekdan** [comment]
My forked repo was a bit of a mess so I've tidied it up and split the bugfix onto a separate branch which i will raise a pr for shortly.

**Pull request closed without merging**
